services:
  - type: web
    name: pokemon-stock-monitor
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: SECRET_KEY
        generateValue: true
      - key: RENDER
        value: true
      - key: FLASK_DEBUG
        value: false
      - key: INTERVALLE_MIN
        value: 1800
      - key: INTERVALLE_MAX
        value: 3600
      - key: PUPPETEER_EXECUTABLE_PATH
        value: /usr/bin/google-chrome-stable
      - key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
        value: true
