services:
  - type: web
    name: pokemon-stock-monitor
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        value: sqlite:///database.db
      - key: FLASK_DEBUG
        value: False
      - key: INTERVALLE_MIN
        value: 540
      - key: INTERVALLE_MAX
        value: 660
