# Workflow pour exécuter le bot Roland Garros périodiquement
name: Roland Garros Bot

# Déclenché selon un calendrier et manuellement
on:
  schedule:
    - cron: '*/30 * * * *'  # Toutes les heures
  workflow_dispatch:  # Permet de déclencher manuellement aussi

# Définition des jobs
jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout du code
      uses: actions/checkout@v3
      
    - name: Configuration de Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Installation des dépendances
      run: pip install -r requirements.txt
      run: pip install chromedriver-autoinstaller && python -c "import chromedriver_autoinstaller; chromedriver_autoinstaller.install()"
      
    - name: Exécution du bot
      run: python roland_garros_bot.py
      env:
        TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        EMAIL_ADDRESS: ${{ secrets.EMAIL_ADDRESS }}
        EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
        EMAIL_RECIPIENT: ${{ secrets.EMAIL_RECIPIENT }}
        TELEPHONE: ${{ secrets.TELEPHONE }}
